### ISSUE TITLE
MySQL u32 overflow at i32::max_value()

### ISSUE THREAD

**Issue by bpbp-boop** [diesel-rs/diesel#1745]
### Versions

- **Rust:** rustc 1.26.1 (827013a31 2018-05-25)
- **Diesel:** 1.3.0
- **Database:** MySQL 8
- **Operating System** CentOS

### Feature Flags

- **diesel:** diesel = { version = "1.0.0", features = ["mysql", "chrono"] }

## Problem Description
Trying to insert a u32 above i32::max_value causes an overflow and database error on MySQL

### Steps to reproduce (reduced testcase)

```rust
#[macro_use]
extern crate diesel;
extern crate dotenv;

use diesel::prelude::*;
use diesel::insert_into;
use dotenv::dotenv;
use std::env;

table! {
    DATA (id) {
        id -> Integer,
        record_id -> Unsigned<Integer>,
        session_id -> Unsigned<Integer>,
    }
}

#[derive(Debug, Insertable)]
#[table_name = "DATA"]
pub struct Data {
    pub record_id: u32,
    pub session_id: u32,
}

fn main() {
    use DATA::dsl::*;

    dotenv().ok();
    let database_url = env::var("DATABASE_URL").expect("DATABASE_URL must be set");
    let connection = MysqlConnection::establish(&database_url)
        .expect(&format!("Error connecting to {}", database_url));

    let i32_max = i32::max_value() as u32;
    let data_ok = Data {
        record_id: 1,
        session_id: i32_max
    };

    insert_into(DATA).values(&data_ok).execute(&connection).unwrap();

    let data_error = Data {
        record_id: 1,
        session_id: i32_max + 1
    };

    insert_into(DATA).values(&data_error).execute(&connection).unwrap();
}
```

### Output
```
    Finished dev [unoptimized + debuginfo] target(s) in 10.45 secs
     Running `target/debug/overflow`

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "Out of range value for column \'session_id\' at row 1")', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  10: overflow::main
             at src/main.rs:46
  11: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: <unknown>


```
Actual SQL executed via the general log
```
2018-06-01T04:52:07.152401Z        74 Query     SET sql_mode=(SELECT CONCAT(@@sql_mode, ',PIPES_AS_CONCAT'))
2018-06-01T04:52:07.152678Z        74 Query     SET time_zone = '+00:00'
2018-06-01T04:52:07.152931Z        74 Query     SET character_set_client = 'utf8mb4'
2018-06-01T04:52:07.153124Z        74 Query     SET character_set_connection = 'utf8mb4'
2018-06-01T04:52:07.153405Z        74 Query     SET character_set_results = 'utf8mb4'
2018-06-01T04:52:07.154014Z        74 Prepare   INSERT INTO `DATA` (`record_id`, `session_id`) VALUES (?, ?)
2018-06-01T04:52:07.154222Z        74 Execute   INSERT INTO `DATA` (`record_id`, `session_id`) VALUES (1, 2147483647)
2018-06-01T04:52:07.323184Z        74 Close stmt
2018-06-01T04:52:07.323492Z        74 Prepare   INSERT INTO `DATA` (`record_id`, `session_id`) VALUES (?, ?)
2018-06-01T04:52:07.323738Z        74 Execute   INSERT INTO `DATA` (`record_id`, `session_id`) VALUES (1, -2147483648)
2018-06-01T04:52:07.324176Z        74 Close stmt
2018-06-01T04:52:07.324698Z        74 Quit
```
## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
That looks strange. We have explicitly a [test case](https://github.com/diesel-rs/diesel/blob/master/diesel_tests/tests/types.rs#L234) testing `u32::max_value()`.

Could you provide the sql that you used to construct your table?

**Comment by sgrif** [comment]
Fixing this is going to require a major version bump :\

**Comment by bpbp-boop** [comment]
Thanks!

**Comment by sgrif** [comment]
1.3.2 has been released with this change.
