### ISSUE TITLE
grouped_by panics if key is not in Parent array

### ISSUE THREAD

**Issue by nishtahir** [diesel-rs/diesel#2298]
### Versions

- **Rust:** nightly-2019-12-22
- **Diesel:** version = "1.4.3", features = ["postgres", "r2d2"]
- **Database:** Postgres
- **Operating System:** macOS

### Feature Flags

- **diesel:**

## Problem Description

```
thread '<unnamed>' panicked at 'no entry found for key', src/libcore/option.rs:1188:5
2020-02-12T12:59:33.327706314Z app[web.1]: stack backtrace:
2020-02-12T12:59:33.329244468Z app[web.1]:    0: backtrace::backtrace::libunwind::trace
2020-02-12T12:59:33.329267263Z app[web.1]:              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
2020-02-12T12:59:33.329297828Z app[web.1]:    1: backtrace::backtrace::trace_unsynchronized
2020-02-12T12:59:33.329303867Z app[web.1]:              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
2020-02-12T12:59:33.329309380Z app[web.1]:    2: std::sys_common::backtrace::_print_fmt
2020-02-12T12:59:33.329314516Z app[web.1]:              at src/libstd/sys_common/backtrace.rs:84
2020-02-12T12:59:33.329319686Z app[web.1]:    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
2020-02-12T12:59:33.329325237Z app[web.1]:              at src/libstd/sys_common/backtrace.rs:61
2020-02-12T12:59:33.329330381Z app[web.1]:    4: core::fmt::write
2020-02-12T12:59:33.329335406Z app[web.1]:              at src/libcore/fmt/mod.rs:1057
2020-02-12T12:59:33.329340266Z app[web.1]:    5: std::io::Write::write_fmt
2020-02-12T12:59:33.329345062Z app[web.1]:              at src/libstd/io/mod.rs:1426
2020-02-12T12:59:33.329349777Z app[web.1]:    6: std::sys_common::backtrace::_print
2020-02-12T12:59:33.329354460Z app[web.1]:              at src/libstd/sys_common/backtrace.rs:65
2020-02-12T12:59:33.329359447Z app[web.1]:    7: std::sys_common::backtrace::print
2020-02-12T12:59:33.329381300Z app[web.1]:              at src/libstd/sys_common/backtrace.rs:50
2020-02-12T12:59:33.329386245Z app[web.1]:    8: std::panicking::default_hook::{{closure}}
2020-02-12T12:59:33.329391124Z app[web.1]:              at src/libstd/panicking.rs:193
2020-02-12T12:59:33.329395879Z app[web.1]:    9: std::panicking::default_hook
2020-02-12T12:59:33.329400595Z app[web.1]:              at src/libstd/panicking.rs:210
2020-02-12T12:59:33.329405309Z app[web.1]:   10: std::panicking::rust_panic_with_hook
2020-02-12T12:59:33.329410008Z app[web.1]:              at src/libstd/panicking.rs:471
2020-02-12T12:59:33.329414696Z app[web.1]:   11: rust_begin_unwind
2020-02-12T12:59:33.329419340Z app[web.1]:              at src/libstd/panicking.rs:375
2020-02-12T12:59:33.329424127Z app[web.1]:   12: core::panicking::panic_fmt
2020-02-12T12:59:33.329428850Z app[web.1]:              at src/libcore/panicking.rs:84
2020-02-12T12:59:33.329433580Z app[web.1]:   13: core::option::expect_failed
2020-02-12T12:59:33.329473776Z app[web.1]:              at src/libcore/option.rs:1188
2020-02-12T12:59:33.329479450Z app[web.1]:   14: <Iter as diesel::associations::belongs_to::GroupedBy<Parent>>::grouped_by
```

I believe the problem is with the map access here
https://docs.diesel.rs/src/diesel/associations/belongs_to.rs.html#128

### What are you trying to accomplish?
I'm trying to group the results by a given list of model IDs. I think that IDs  that are not represented should be ignored but at the very least should not cause a panic

### What is the expected output?
It should not panic

### What is the actual output?
It currently panics with the backtrace provided above

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Can you please provide a minimal example how to trigger this?

**Comment by nishtahir** [comment]
@weiznich i've put together a sample demonstrating the issue here
https://github.com/nishtahir/diesel-issues-2298

**Comment by weiznich** [comment]
@nishtahir Thanks for putting together the reproducible example. I think `.grouped_by` is designed to be called with the same list of elements passed to `belongs_to`, so that this is just a use case we did'nt design the API for. That said it is probably useful to also support this, but I need to think about what's the right behaviour here.

**Comment by Wolveric** [comment]
I just encountered this behaviour today, and I would like to highlight how the method should potentially behave when encountering Child entries without a corresponding Parent:

---

### Option 1: Panic

The current behaviour, but seemingly an oversight... as it panics rather than producing a `Result`, `GroupedBy::grouped_by` would have to be called in a context where the panic can be caught, to depend on the current behaviour.

As any current cases using this behaviour would have to be actively designed around recovering from a panic, panicking presumably still is not desirable...

---

### Option 2: Ignore Child entries without a corresponding Parent

A choice that would actually make a lot of sense... the current implementation already behaves somewhat like a `LEFT OUTER JOIN`, dropping any Child entries where the foreign key is `NULL`/Option::None`, and so can't have a Parent entry... it would be reasonable to extend the same behaviour to Child entries without parents in the current slice, as these would also have been excluded from a `LEFT OUTER JOIN`...

It's also a simple change, with no effect on the current trait or implementation signature. Switching from `Option::map` and `HashMap::index` to `Option::and_then` and `HashMap::get`.

Arguably, this does have the downside use cases that previously handled panicking, will now instead continue with potentially unexpected set of entries... likely in this case, fewer than expected...

---

### Option 3: Return a `Result`

Using this option would significantly deviate from the current behaviour of the `GroupedBy::grouped_by` method, and would require changing its signature, but would allow for more detail in describing what occurred while executing the method... consequently, as `GroupedBy` is a trait, it does pose a simple solution to supporting this option though: Another trait of a similar style e.g. `TryGroupedBy`

In this case, it may be relevant to take inspiration from `PoisonError` type, using the `Err` variant to return a collection of unrelated entries in case an API consumer wishes to make use of them, alongside the potentially incomplete grouped entries, to ensure it's clearly indicated this result may not be complete.

**Comment by weiznich** [comment]
I fear option 3 is not really possible at the time of writing as that would require changing the signature of the `grouped_by` method, which in turn is a breaking change and would require a major version bump. 

What we could to and what in my opinion sounds reasonable is implementing the following solution:

* Add a new method to the `GroupedBy` trait, lets call it `try_grouped_by` for now (I'm not 100% sold on that name, likely we want something better) that returns a `Result` instead
    + This method should have a default implementation just forwarding to the existing `GroupedBy::grouped_by` method to make adding this new method to the public trait not a breaking change.
    + Including a list of rejected values in the error sounds reasonable
* Change all existing impls of `GroupedBy` in diesel to implement `try_grouped_by` instead of `grouped_by` to avoid this panic.
* Also implement `grouped_by` for all existing impls in diesel to internally call the `try_grouped_by` method and unwrap the result.
* Possibly we might want to deprecate the old method at some point.

This would retain the behavior of the existing API while providing a new API that allows users to opt into the new behavior. 

This needs to come with some documentation and tests for the new method. 

I'm happy to review a PR for this.

**Comment by Wolveric** [comment]
I noted the signature wouldn't have to be changed, if it was a separate trait, 

It also wouldn't put the burden of implementing a new method for the existing trait on external implementors,

**Comment by Wolveric** [comment]
Following some further thought, something of a correction on my part:

I didn't quite follow the response to my comment, but now I understand the suggestion about adding the method to the existing trait... whilst slightly confusing, I can see how a default implementation of `GroupedBy::try_group_by` could work, by always returning the `Ok` variant. 

I think updating `GroupedBy::grouped_by` to call `GroupedBy::try_group_by` would be a mistake though, as collecting the ungrouped records would be significantly more work than simply discarding them, especially implicitly.
