### ISSUE TITLE
order_by_column test is not deterministic

### ISSUE THREAD

**Issue by Ploppz** [diesel-rs/diesel#2949]
I'm in my own branch (`only`) which builds from b2c58897c3.
I have ran `cargo test --features postgres` many times. Only once, I got one failed test (that my code could not possibly affect I think?):

```
failures:

---- order::order_by_column stdout ----
thread 'order::order_by_column' panicked at 'assertion failed: `(left == right)`
  left: `[User { id: 275, name: "Aaron", hair_color: None }, User { id: 275, name: "Jim", hair_color: None }, User { id: 273, name: "Sean", hair_color: None }, User { id: 274, name: "Tess", hair_color: None }]`,
 right: `[User { id: 55, name: "Aaron", hair_color: None }, User { id: 275, name: "Jim", hair_color: None }, User { id: 273, name: "Sean", hair_color: None }, User { id: 274, name: "Tess", hair_color: None }]`', diesel_tests/tests/order.rs:40:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: integration_tests::order::order_by_column
             at ./tests/order.rs:40:5
   3: integration_tests::order::order_by_column::{{closure}}
             at ./tests/order.rs:5:1
   4: core::ops::function::FnOnce::call_once
             at /home/erlend/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    order::order_by_column

test result: FAILED. 363 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 41.36s
```

In any case, this test passed right after it failed without any changes to the code.

**Comment by weiznich** [comment]
That's something I noticed as well, but I've never had the time and motivation to track this down. If someone knows more about how to reproduce this please leave a comment here.

**Comment by ayarotsky** [comment]
@weiznich do you mind if I take this one?
