### ISSUE TITLE
[bug] PgConnection establish connection error with READONLY user

### ISSUE THREAD

**Issue by himitsuko** [diesel-rs/diesel#3261]
### Versions

- **Rust:** 1.62.1
- **Diesel:** 1.4.4
- **Database:** 14
- **Operating System** MacOS 12.2.1

### Feature Flags

- **diesel:** ["postgres"]

## Problem Description
I'm trying to connect to a public postgresql database with read only user at : `postgres://public_readonly:nearprotocol@mainnet.db.explorer.indexer.near.dev:5432/mainnet_explorer`
However the connection throw the error as the `What is the actual output?` section.

### What are you trying to accomplish?
I'm trying to find the way to establish connection with readonly user from [near indexer](https://github.com/near/near-indexer-for-explorer)

### What is the expected output?
It can connect without the panic.

### What is the actual output?
```bash
thread '<unnamed>' panicked at 'Error connecting to postgres://public_readonly:nearprotocol@mainnet.db.explorer.indexer.near.dev:5432/mainnet_explorer: CouldntSetupConfiguration(DatabaseError(__Unknown, "unnamed prepared statement does not exist"))', src/connection/postgresql.rs:30:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1035:23
   4: depocket_near_indexer::connection::postgresql::establish_connection
             at ./src/connection/postgresql.rs:29:5
   5: depocket_near_indexer::handle_index_old_data
             at ./src/main.rs:98:35
   6: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'Old block handle panic!: Any { .. }', src/main.rs:85:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1035:23
   4: depocket_near_indexer::main::{{closure}}
             at ./src/main.rs:85:5
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
   6: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/sensitive/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
   7: tokio::coop::with_budget::{{closure}}
             at /Users/sensitive/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
   8: std::thread::local::LocalKey<T>::try_with
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/local.rs:445:16
   9: std::thread::local::LocalKey<T>::with
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/local.rs:421:9
  10: tokio::coop::with_budget
             at /Users/sensitive/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  11: tokio::coop::budget
             at /Users/sensitive/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  12: tokio::park::thread::CachedParkThread::block_on
             at /Users/sensitive/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:31
  13: tokio::runtime::enter::Enter::block_on
             at /Users/sensitive/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/enter.rs:151:13
  14: tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/sensitive/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/mod.rs:73:9
  15: tokio::runtime::Runtime::block_on
             at /Users/sensitive/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:477:43
  16: depocket_near_indexer::main
             at ./src/main.rs:94:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Are you seeing any additional errors?
N/A

### Steps to reproduce

```
use diesel::pg::PgConnection;

fn main() {
PgConnection::establish(&String::from("postgres://public_readonly:nearprotocol@mainnet.db.explorer.indexer.near.dev:5432/mainnet_explorer"))
        .expect(&format!("Error connecting to {}", database_url))
}

```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
The error message indicates that your database does not allow the creation of prepared statements. This is something that is fundamentally needed by `PgConnection` so it's expected that it does not work with database that do not allow this operation.

Closed as this issue indicates that the corresponding database just does not support required features.

**Comment by himitsuko** [comment]
I got it,
Thank you!
