### ISSUE TITLE
Windows CI is failing to install postgres

### ISSUE THREAD

**Issue by jayvdb** [diesel-rs/diesel#3960]
See https://github.com/diesel-rs/diesel/actions/runs/8217715890/job/22473728471?pr=3959

It looks like the error is that `choco install` now needs creds to access the API.
```
Invalid credentials specified.
Please provide credentials for: https://community.chocolatey.org/api/v2/
```

Full log

```
Run choco install postgresql12 --force --params '/Password:root'
  choco install postgresql1[2](https://github.com/diesel-rs/diesel/actions/runs/8217715890/job/22473728471?pr=3959#step:14:2) --force --params '/Password:root'
  echo "C:\Program Files\PostgreSQL\12\bin" >> $GITHUB_PATH
  echo "C:\Program Files\PostgreSQL\12\lib" >> $GITHUB_PATH
  echo "PQ_LIB_DIR=C:\Program Files\PostgreSQL\12\lib" >> $GITHUB_ENV
  echo "PG_DATABASE_URL=***localhost/" >> $GITHUB_ENV
  echo "PG_EXAMPLE_DATABASE_URL=***localhost/diesel_example" >> $GITHUB_ENV
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
Chocolatey v2.2.2
Installing the following packages:
postgresql12
By installing, you accept licenses for the packages.
Invalid credentials specified.
Please provide credentials for: https://community.chocolatey.org/api/v2/
User name: Password: Chocolatey had an error on fv-az978-[6](https://github.com/diesel-rs/diesel/actions/runs/8217715890/job/22473728471?pr=3959#step:14:6)9[7](https://github.com/diesel-rs/diesel/actions/runs/8217715890/job/22473728471?pr=3959#step:14:7) (with user runneradmin):
System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at chocolatey.infrastructure.commandline.ReadKeyTimeout.ConsoleReadKey()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at chocolatey.infrastructure.commandline.ReadKeyTimeout.ConsoleReadKey()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Error: Process completed with exit code [12](https://github.com/diesel-rs/diesel/actions/runs/8217715890/job/22473728471?pr=3959#step:14:13)7.
```

**Comment by jayvdb** [comment]
See also https://github.com/actions/runner-images/issues/9477

**Comment by jayvdb** [comment]
Problem fixed.
